from PyQt5.QtGui import QColor
from PyQt5.QtCore import QRegExp


VIOLET2 = QColor(101, 84, 193)
ROUGE = QColor(255, 0, 0)
ROUGE_FONCE = QColor(144, 12, 40)
CYAN = QColor(28, 195, 173)
VIOLET = QColor(141, 29, 117)
GRIS = QColor(153, 153, 153)
BLEU_FONCE = QColor(38, 21, 232)
VERT = QColor(0, 197, 6)
BLEU_PASTEL = QColor(30, 95,164)
ORANGE = QColor(210, 100, 40)
VERT_POMME = QColor(37, 142, 0)
COULEURS = {"rouge" : ROUGE, "rouge_fonce" : ROUGE_FONCE, "cyan" : CYAN, "violet" : VIOLET, "gris" : GRIS, "bleu_fonce" : BLEU_FONCE,
            "vert" : VERT, "bleu_pastel" : BLEU_PASTEL, "orange" : ORANGE, "vert_pomme" : VERT_POMME, "violet2" : VIOLET2}

HIGHLIGHTING_RULES : tuple[tuple[QRegExp, QColor, bool]] = (
                      (QRegExp("\\bfor\\b"), "rouge_fonce", True),
                      (QRegExp("\\bwhile\\b"), "rouge_fonce", True),
                      (QRegExp("\\bin\\b"), "rouge_fonce", True),
                      (QRegExp("\\bdef\\b"), "bleu_fonce", True),
                      (QRegExp("\\breturn\\b"), "bleu_fonce", True),
                      (QRegExp("\\bdel\\b"), "bleu_fonce", True),
                      (QRegExp("\\bclass\\b"), "bleu_fonce", True),
                      (QRegExp("\\bif\\b"), "rouge_fonce", True),
                      (QRegExp("\\belif\\b"), "rouge_fonce", True),
                      (QRegExp("\\belse\\b"), "rouge_fonce", True),
                      (QRegExp("\\bwith\\b"), "rouge_fonce", True),
                      (QRegExp("\\bas\\b"), "rouge_fonce", True),
                      (QRegExp("\\band\\b"), "vert", True),
                      (QRegExp("\\bor\\b"), "vert", True),
                      (QRegExp("\\bnot\\b"), "vert", True),
                      (QRegExp("\\bis\\b"), "violet", False),
                      (QRegExp("\\bNone\\b"), "violet", False),
                      (QRegExp("\\bTrue\\b"), "violet", False),
                      (QRegExp("\\bFalse\\b"), "violet", False),
                      (QRegExp("\\brange\\b"), "cyan", False),
                      (QRegExp("\\bprint\\b"), "cyan", False),
                      (QRegExp("\\bsplit\\b"), "cyan", False),
                      (QRegExp("\\binsert\\b"), "cyan", False),
                      (QRegExp("\\bcount\\b"), "cyan", False),
                      (QRegExp("\\bremove\\b"), "cyan", False),
                      (QRegExp("\\bextend\\b"), "cyan", False),
                      (QRegExp("\\bappend\\b"), "cyan", False),
                      (QRegExp("\\bindex\\b"), "cyan", False),
                      (QRegExp("\\bclear\\b"), "cyan", False),
                      (QRegExp("\\bopen\\b"), "cyan", False),
                      (QRegExp("\\bclose\\b"), "cyan", False),
                      (QRegExp("\\bcopy\\b"), "cyan", False),
                      (QRegExp("\\bsort\\b"), "cyan", False),
                      (QRegExp("\\bpop\\b"), "cyan", False),
                      (QRegExp("\\breverse\\b"), "cyan", False),
                      (QRegExp("\\binput\\b"), "cyan", False),
                      (QRegExp("\\bzip\\b"), "cyan", False),
                      (QRegExp("\\bget\\b"), "cyan", False),
                      (QRegExp("\\babs\\b"), "cyan", False),
                      (QRegExp("\\ball\\b"), "cyan", False),
                      (QRegExp("\\bany\\b"), "cyan", False),
                      (QRegExp("\\bbin\\b"), "cyan", False),
                      (QRegExp("\\bcallable\\b"), "cyan", False),
                      (QRegExp("\\bcapitalize\\b"), "cyan", False),
                      (QRegExp("\\bisaplpha\\b"), "cyan", False),
                      (QRegExp("\\bchoice\\b"), "cyan", False),
                      (QRegExp("\\bendswith\\b"), "cyan", False),
                      (QRegExp("\\bstartswith\\b"), "cyan", False),
                      (QRegExp("\\bisdigit\\b"), "cyan", False),
                      (QRegExp("\\bisupper\\b"), "cyan", False),
                      (QRegExp("\\bislower\\b"), "cyan", False),
                      (QRegExp("\\bistitle\\b"), "cyan", False),
                      (QRegExp("\\bisspace\\b"), "cyan", False),
                      (QRegExp("\\blower\\b"), "cyan", False),
                      (QRegExp("\\bupper\\b"), "cyan", False),
                      (QRegExp("\\bfind\\b"), "cyan", False),
                      (QRegExp("\\bjoin\\b"), "cyan", False),
                      (QRegExp("\\blstrip\\b"), "cyan", False),
                      (QRegExp("\\brstrip\\b"), "cyan", False),
                      (QRegExp("\\bstrip\\b"), "cyan", False),
                      (QRegExp("\\bisdecimal\\b"), "cyan", False),
                      (QRegExp("\\bformat\\b"), "cyan", False),
                      (QRegExp("\\bmap\\b"), "cyan", False),
                      (QRegExp("\\benumerate\\b"), "cyan", False),
                      (QRegExp("\\bexec\\b"), "cyan", False),
                      (QRegExp("\\beval\\b"), "cyan", False),
                      (QRegExp("\\bint\\b"), "violet2", False),
                      (QRegExp("\\bstr\\b"), "violet2", False),
                      (QRegExp("\\btype\\b"), "violet2", False),
                      (QRegExp("\\bcomplex\\b"), "violet2", False),
                      (QRegExp("\\bbool\\b"), "violet2", False),
                      (QRegExp("\\btuple\\b"), "violet2", False),
                      (QRegExp("\\bset\\b"), "violet2", False),
                      (QRegExp("\\bfloat\\b"), "violet2", False),
                      (QRegExp("\\blist\\b"), "violet2", False),
                      (QRegExp("\\bdict\\b"), "violet2", False),
                      (QRegExp("[=-\*\+/%]"), "gris", False),
                      (QRegExp("[0-9_]+"), "bleu_pastel", False),
                      (QRegExp("=="), "gris", False),
                      (QRegExp("<="), "gris", False),
                      (QRegExp(">="), "gris", False),
                      (QRegExp(">"), "gris", False),
                      (QRegExp("<"), "gris", False),
                      (QRegExp("!="), "gris", False),
                      (QRegExp("\[|\]|\(|\)|\{|\}"), "vert_pomme", False),
                      (QRegExp("#[^\\n]*"),"gris", False),
                      (QRegExp("={3,}|[-+*%]{2,}|/{3,}"), "rouge", False),  # à partir d'ici, il s'agit d'erreurs
                      (QRegExp("=[<>!-*+\\\/%]+"), "rouge", False),
                      (QRegExp("[<>!/%-+*\]+=="), "rouge", False),
                      (QRegExp("[^a-zA-Z]+\\d+[a-zA-Z]+"), "rouge", False),
                      (QRegExp("(\([^)\"']*(\]|\}))|((\[|\{)[^(\"']*\))"), "rouge", False),
                      (QRegExp("(\[[^\]\"']*\})|(\{[^\[\"']*\])"), "rouge", False),
                      (QRegExp("\\brange\\b\( *\)"), "rouge", False),
                      (QRegExp("\\brange\\b\(\".*\)"), "rouge", False),
                      (QRegExp("\\brange\\b\([^0-9]*\)"), "rouge", False),
                      (QRegExp("(?\\bdef\\b)[^a\\n:]*a(\\n|\\r)"), "rouge", False),
                      (QRegExp("\"[^\"]*\""), "orange", False),             # sauf ces deux dernières expressions
                      (QRegExp("\'[^\']*\'"), "orange", False),             # qui gèrent la coloration des strings
                      )

HIGHLIGHTING_NIVEAU = {
    1 : QRegExp("\\b(est_creature)\\b"),
    2 : QRegExp("\\b(evaluation_gobelin)\\b"),
    3 : QRegExp("\\b(pierre_cassable)\\b"),
    4 : QRegExp("\\b(trouver_squelette)\\b"),
    5 : QRegExp("\\b(inverse_dialogue)\\b"),
    6 : QRegExp("\\b(araignee_euler)\\b"),
    7 : QRegExp("\\b(est_pangramme)\\b"),
    8 : QRegExp("\\b(mystere)\\b"),
    9 : QRegExp("\\b(decrypte_cesar)\\b"),
    10 : QRegExp("\\b(passage_possible)\\b"),
    11 : QRegExp("\\b(nombre_riposte)\\b"),
    12 : QRegExp("\\b(bloque_anagramme)\\b"),
    13 : QRegExp("\\b(melange)\\b"),
    14 : QRegExp("\\b(is_fibonacci)\\b"),
    15 : QRegExp("\\b(retourne_sort)\\b")
}